# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{log_master}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zachary Belzer"]
  s.date = %q{2009-12-01}
  s.description = %q{Creates and emails a simple report for a set of log (or text) files. Useful for aggretating small log files.}
  s.email = %q{zbelzer@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/log_master.feature",
     "features/step_definitions/email_steps.rb",
     "features/step_definitions/log_master_steps.rb",
     "features/support/env.rb",
     "init.rb",
     "lib/log_master.rb",
     "lib/log_master/configuration.rb",
     "lib/log_master/director.rb",
     "lib/log_master/log_file.rb",
     "lib/log_master/notifier.rb",
     "lib/log_master/rake/log_task.rb",
     "lib/templates/log_master/notifier/update_notification.html.erb",
     "log_master.gemspec",
     "spec/configuration_spec.rb",
     "spec/director_spec.rb",
     "spec/fixtures/empty_log.log",
     "spec/fixtures/log_with_errors.log",
     "spec/fixtures/log_without_errors.log",
     "spec/log_file_spec.rb",
     "spec/notification_spec.rb",
     "spec/spec_helper.rb",
     "tasks/log_master.rake"
  ]
  s.homepage = %q{http://github.com/moneypools/log_master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Creates and emails a simple report for a set of log (or text) files. Useful for aggretating small log files.}
  s.test_files = [
    "spec/configuration_spec.rb",
     "spec/director_spec.rb",
     "spec/log_file_spec.rb",
     "spec/notification_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionmailer>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<email_spec>, [">= 0.3.5"])
    else
      s.add_dependency(%q<actionmailer>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<email_spec>, [">= 0.3.5"])
    end
  else
    s.add_dependency(%q<actionmailer>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<email_spec>, [">= 0.3.5"])
  end
end
